server:
  port: 8080
spring:
  thymeleaf:
    cache: true
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true&autoReconnect=true
    username: root
    password: mysql_zhouhua
    hikari:
      max-lifetime: 60000
# log 配置
logging:
  file: data/logs/blog.log
  level:
    com:
      iszhouhua:
        blog: info